In [1]:
!pip install numpy

You should consider upgrading via the 'c:\users\mohammad\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np
import pandas as pd

In [3]:
data_preprocessed = pd.read_csv('Final_Absenteeism_preprocessed.csv')

In [4]:
data_preprocessed.head()

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                5   
1        0        0        0        0            7                5   
2        0        0        0        1            7                6   
3        1        0        0        0            7                0   
4        0        0        0        1            7                0   

         Date  Transportation Expense  Distance to Work  Age  \
0  2018-07-07                     289                36   33   
1  2018-07-14                     118                13   50   
2  2018-07-15                     179                51   38   
3  2018-07-16                     279                 5   39   
4  2018-07-23                     289                36   33   

   Daily Work Load Average(in Minutes)   Body Mass Index  Education  Children  \
0                               239.554               30          0         2   
1                               239.554               31          0         1   
2                               239.554               31          0         0   
3                               239.554               24          0         2   
4                               239.554               30          0         2   

   Pets  Absenteeism Time in Hours  
0     1                          4  
1     0                          0  
2     0                          2  
3     0                          4  
4     1                          2

In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
data_preprocessed['Excessive Absenteeism'] = targets

In [9]:
data_preprocessed.head()

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                5   
1        0        0        0        0            7                5   
2        0        0        0        1            7                6   
3        1        0        0        0            7                0   
4        0        0        0        1            7                0   

         Date  Transportation Expense  Distance to Work  Age  \
0  2018-07-07                     289                36   33   
1  2018-07-14                     118                13   50   
2  2018-07-15                     179                51   38   
3  2018-07-16                     279                 5   39   
4  2018-07-23                     289                36   33   

   Daily Work Load Average(in Minutes)   Body Mass Index  Education  Children  \
0                               239.554               30          0         2   
1                               239.554               31          0         1   
2                               239.554               31          0         0   
3                               239.554               24          0         2   
4                               239.554               30          0         2   

   Pets  Absenteeism Time in Hours  Excessive Absenteeism  
0     1                          4                      1  
1     0                          0                      0  
2     0                          2                      0  
3     0                          4                      1  
4     1                          2                      0

In [10]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [11]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Date', 'Daily Work Load Average(in Minutes) ', 
                                            'Distance to Work'],axis=1)

In [12]:
data_with_targets.head()

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                5   
1        0        0        0        0            7                5   
2        0        0        0        1            7                6   
3        1        0        0        0            7                0   
4        0        0        0        1            7                0   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [13]:
data_with_targets.shape[1]

13

In [14]:
data_with_targets.iloc[:,0:14]

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0          0        0        0        1            7                5   
1          0        0        0        0            7                5   
2          0        0        0        1            7                6   
3          1        0        0        0            7                0   
4          0        0        0        1            7                0   
..       ...      ...      ...      ...          ...              ...   
695        1        0        0        0            5                6   
696        1        0        0        0            5                6   
697        1        0        0        0            5                0   
698        0        0        0        1            5                0   
699        0        0        0        1            5                0   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 13 columns]

In [15]:
data_with_targets.iloc[:,0:-1]

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0          0        0        0        1            7                5   
1          0        0        0        0            7                5   
2          0        0        0        1            7                6   
3          1        0        0        0            7                0   
4          0        0        0        1            7                0   
..       ...      ...      ...      ...          ...              ...   
695        1        0        0        0            5                6   
696        1        0        0        0            5                6   
697        1        0        0        0            5                0   
698        0        0        0        1            5                0   
699        0        0        0        1            5                0   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 12 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [17]:
unscaled_inputs

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0          0        0        0        1            7                5   
1          0        0        0        0            7                5   
2          0        0        0        1            7                6   
3          1        0        0        0            7                0   
4          0        0        0        1            7                0   
..       ...      ...      ...      ...          ...              ...   
695        1        0        0        0            5                6   
696        1        0        0        0            5                6   
697        1        0        0        0            5                0   
698        0        0        0        1            5                0   
699        0        0        0        1            5                0   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 12 columns]

In [18]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\mohammad\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [19]:
from sklearn.preprocessing import StandardScaler

In [20]:
from sklearn.base import BaseEstimator, TransformerMixin

In [21]:
class CustomScaler(BaseEstimator, TransformerMixin):
    
    def __init__(self,columns):
        self.scaler = StandardScaler()
        self.columns = columns
        self.mean_ = None
        self.var = None
        
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns],y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns = self.columns)
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled],axis=1)[init_col_order]

In [22]:
unscaled_inputs.columns.values

array(['reason1', 'reason2', 'reason3', 'reason4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [23]:
#columns_to_scale = ['Month Value', 'Day of the Week', 'Transportation Expense', 'Distance to Work', 'Age', 
                    #'Daily Work Load Average(in Minutes) ', 'Body Mass Index', 'Children', 'Pets']
columns_to_omit = ['reason_1', 'reason_2', 'reason_3', 'reason_4', 'Education']

In [24]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [25]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [26]:
absenteeism_scaler.fit(unscaled_inputs)

c:\users\mohammad\appdata\local\programs\python\python39\lib\site-packages\numpy\core\fromnumeric.py:3472: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


CustomScaler(columns=['reason1', 'reason2', 'reason3', 'reason4', 'Month Value',
                      'Day of the Week', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [27]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [28]:
scaled_inputs

reason1   reason2   reason3   reason4  Month Value  Day of the Week  \
0   -0.577350 -0.092981 -0.396264  0.901927     0.182726         0.721406   
1   -0.577350 -0.092981 -0.396264 -1.108738     0.182726         0.721406   
2   -0.577350 -0.092981 -0.396264  0.901927     0.182726         1.176756   
3    1.732051 -0.092981 -0.396264 -1.108738     0.182726        -1.555348   
4   -0.577350 -0.092981 -0.396264  0.901927     0.182726        -1.555348   
..        ...       ...       ...       ...          ...              ...   
695  1.732051 -0.092981 -0.396264 -1.108738    -0.388293         1.176756   
696  1.732051 -0.092981 -0.396264 -1.108738    -0.388293         1.176756   
697  1.732051 -0.092981 -0.396264 -1.108738    -0.388293        -1.555348   
698 -0.577350 -0.092981 -0.396264  0.901927    -0.388293        -1.555348   
699 -0.577350 -0.092981 -0.396264  0.901927    -0.388293        -1.555348   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 12 columns]

In [29]:
scaled_inputs.shape

(700, 12)

In [30]:
#absenteeim_scaler = StandardScaler()

In [31]:
#absenteeim_scaler.fit(unscaled_inputs)

In [32]:
#scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [33]:
#scaled_inputs

In [34]:
#scaled_inputs.shape

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
train_test_split(scaled_inputs,targets)

[     reason1   reason2   reason3   reason4  Month Value  Day of the Week  \
 685 -0.57735 -0.092981 -0.396264  0.901927    -0.388293         0.266055   
 604 -0.57735 -0.092981 -0.396264  0.901927    -1.244823         1.176756   
 633 -0.57735 -0.092981 -0.396264  0.901927    -0.959313        -1.099997   
 152 -0.57735 -0.092981 -0.396264  0.901927    -1.244823         0.721406   
 375 -0.57735 -0.092981 -0.396264  0.901927    -1.244823        -0.189296   
 ..       ...       ...       ...       ...          ...              ...   
 541 -0.57735 -0.092981 -0.396264  0.901927     1.324766         1.176756   
 684 -0.57735 -0.092981 -0.396264  0.901927    -0.388293        -1.099997   
 110 -0.57735 -0.092981 -0.396264  0.901927     1.610276        -1.099997   
 68  -0.57735 -0.092981 -0.396264  0.901927     1.039256         0.721406   
 388 -0.57735 -0.092981 -0.396264  0.901927    -1.244823         0.721406   
 
      Transportation Expense       Age  Body Mass Index  Education  Childr

In [37]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets,train_size = 0.8, test_size = 0.2, random_state = 20)

In [38]:
x_train.shape, y_train.shape

((560, 12), (560,))

In [39]:
x_test.shape, y_test.shape

((140, 12), (140,))

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
reg = LogisticRegression()

In [42]:
reg.fit(x_train, y_train)

LogisticRegression()

In [43]:
reg.score(x_train, y_train)

0.8053571428571429

In [44]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [45]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [46]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [47]:
np.sum((model_outputs == y_train))

451

In [48]:
model_outputs.shape[0]

560

In [49]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.8053571428571429

In [50]:
reg.intercept_

array([-0.10676095])

In [51]:
reg.coef_

array([[ 2.01472593,  0.33046133,  1.93075387,  1.17284325,  0.25230956,
         0.02892238,  0.62784796, -0.19012251,  0.29876922, -0.49365429,
         0.33058678, -0.49797138]])

In [52]:
#unscaled_inputs.columns.values

In [53]:
feature_names = unscaled_inputs.columns.values

In [54]:
summary_table = pd.DataFrame(columns=['feature name'], data = feature_names)

In [55]:
summary_table['Coefficient'] = np.transpose(reg.coef_)

In [56]:
summary_table

feature name  Coefficient
0                  reason1     2.014726
1                  reason2     0.330461
2                  reason3     1.930754
3                  reason4     1.172843
4              Month Value     0.252310
5          Day of the Week     0.028922
6   Transportation Expense     0.627848
7                      Age    -0.190123
8          Body Mass Index     0.298769
9                Education    -0.493654
10                Children     0.330587
11                    Pets    -0.497971

In [57]:
summary_table.index = summary_table.index + 1

In [58]:
summary_table

feature name  Coefficient
1                  reason1     2.014726
2                  reason2     0.330461
3                  reason3     1.930754
4                  reason4     1.172843
5              Month Value     0.252310
6          Day of the Week     0.028922
7   Transportation Expense     0.627848
8                      Age    -0.190123
9          Body Mass Index     0.298769
10               Education    -0.493654
11                Children     0.330587
12                    Pets    -0.497971

In [59]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table

feature name  Coefficient
1                  reason1     2.014726
2                  reason2     0.330461
3                  reason3     1.930754
4                  reason4     1.172843
5              Month Value     0.252310
6          Day of the Week     0.028922
7   Transportation Expense     0.627848
8                      Age    -0.190123
9          Body Mass Index     0.298769
10               Education    -0.493654
11                Children     0.330587
12                    Pets    -0.497971
0                Intercept    -0.106761

In [60]:
summary_table = summary_table.sort_index()
summary_table

feature name  Coefficient
0                Intercept    -0.106761
1                  reason1     2.014726
2                  reason2     0.330461
3                  reason3     1.930754
4                  reason4     1.172843
5              Month Value     0.252310
6          Day of the Week     0.028922
7   Transportation Expense     0.627848
8                      Age    -0.190123
9          Body Mass Index     0.298769
10               Education    -0.493654
11                Children     0.330587
12                    Pets    -0.497971

In [61]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [62]:
summary_table

feature name  Coefficient  Odds_ratio
0                Intercept    -0.106761    0.898740
1                  reason1     2.014726    7.498672
2                  reason2     0.330461    1.391610
3                  reason3     1.930754    6.894706
4                  reason4     1.172843    3.231167
5              Month Value     0.252310    1.286994
6          Day of the Week     0.028922    1.029345
7   Transportation Expense     0.627848    1.873574
8                      Age    -0.190123    0.826858
9          Body Mass Index     0.298769    1.348198
10               Education    -0.493654    0.610392
11                Children     0.330587    1.391785
12                    Pets    -0.497971    0.607762

In [63]:
summary_table.sort_values('Odds_ratio', ascending=False)

feature name  Coefficient  Odds_ratio
1                  reason1     2.014726    7.498672
3                  reason3     1.930754    6.894706
4                  reason4     1.172843    3.231167
7   Transportation Expense     0.627848    1.873574
11                Children     0.330587    1.391785
2                  reason2     0.330461    1.391610
9          Body Mass Index     0.298769    1.348198
5              Month Value     0.252310    1.286994
6          Day of the Week     0.028922    1.029345
0                Intercept    -0.106761    0.898740
8                      Age    -0.190123    0.826858
10               Education    -0.493654    0.610392
12                    Pets    -0.497971    0.607762

In [64]:
reg.score(x_test, y_test)

0.7714285714285715

In [65]:
predicted_probability = reg.predict_proba(x_test)

predicted_probability

array([[0.70558741, 0.29441259],
       [0.64136716, 0.35863284],
       [0.41992231, 0.58007769],
       [0.81005131, 0.18994869],
       [0.06744317, 0.93255683],
       [0.29239465, 0.70760535],
       [0.33588346, 0.66411654],
       [0.06978632, 0.93021368],
       [0.87243296, 0.12756704],
       [0.749575  , 0.250425  ],
       [0.06639241, 0.93360759],
       [0.01188904, 0.98811096],
       [0.03414062, 0.96585938],
       [0.15912287, 0.84087713],
       [0.1912779 , 0.8087221 ],
       [0.63752808, 0.36247192],
       [0.73027194, 0.26972806],
       [0.09199825, 0.90800175],
       [0.42560422, 0.57439578],
       [0.02204801, 0.97795199],
       [0.75459217, 0.24540783],
       [0.81206946, 0.18793054],
       [0.3344868 , 0.6655132 ],
       [0.32864923, 0.67135077],
       [0.17182348, 0.82817652],
       [0.81509167, 0.18490833],
       [0.53860466, 0.46139534],
       [0.89248965, 0.10751035],
       [0.07886111, 0.92113889],
       [0.79971186, 0.20028814],
       [0.

In [66]:
predicted_probability.shape

(140, 2)

In [67]:
predicted_probability[:,1]

array([0.29441259, 0.35863284, 0.58007769, 0.18994869, 0.93255683,
       0.70760535, 0.66411654, 0.93021368, 0.12756704, 0.250425  ,
       0.93360759, 0.98811096, 0.96585938, 0.84087713, 0.8087221 ,
       0.36247192, 0.26972806, 0.90800175, 0.57439578, 0.97795199,
       0.24540783, 0.18793054, 0.6655132 , 0.67135077, 0.82817652,
       0.18490833, 0.46139534, 0.10751035, 0.92113889, 0.20028814,
       0.92335719, 0.63846904, 0.73649999, 0.94199918, 0.18793054,
       0.95458914, 0.13580166, 0.85848038, 0.32835048, 0.57261273,
       0.18499416, 0.39860608, 0.15361393, 0.11922121, 0.82435883,
       0.75448572, 0.72617333, 0.29168419, 0.18737121, 0.16876331,
       0.60992057, 0.0847821 , 0.70760535, 0.2724392 , 0.8539586 ,
       0.40186033, 0.90007717, 0.19502251, 0.10530085, 0.10464486,
       0.69468429, 0.69527866, 0.28899475, 0.88204731, 0.12205553,
       0.2784279 , 0.02164948, 0.14371664, 0.86737643, 0.8757643 ,
       0.13580166, 0.07717457, 0.93719845, 0.40251901, 0.56245

In [68]:
import pickle

In [69]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)

In [70]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)