In [1]:
!pip install numpy

You should consider upgrading via the 'c:\users\mohammad\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np
import pandas as pd

In [3]:
data_preprocessed = pd.read_csv('Final_Absenteeism_preprocessed.csv')

In [4]:
data_preprocessed.head()

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                5   
1        0        0        0        0            7                5   
2        0        0        0        1            7                6   
3        1        0        0        0            7                0   
4        0        0        0        1            7                0   

         Date  Transportation Expense  Distance to Work  Age  \
0  2018-07-07                     289                36   33   
1  2018-07-14                     118                13   50   
2  2018-07-15                     179                51   38   
3  2018-07-16                     279                 5   39   
4  2018-07-23                     289                36   33   

   Daily Work Load Average(in Minutes)   Body Mass Index  Education  Children  \
0                               239.554               30          0         2   
1                               239.554               31          0         1   
2                               239.554               31          0         0   
3                               239.554               24          0         2   
4                               239.554               30          0         2   

   Pets  Absenteeism Time in Hours  
0     1                          4  
1     0                          0  
2     0                          2  
3     0                          4  
4     1                          2

In [5]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [6]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 3, 1, 0)

In [7]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [8]:
data_preprocessed['Excessive Absenteeism'] = targets

In [9]:
data_preprocessed.head()

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                5   
1        0        0        0        0            7                5   
2        0        0        0        1            7                6   
3        1        0        0        0            7                0   
4        0        0        0        1            7                0   

         Date  Transportation Expense  Distance to Work  Age  \
0  2018-07-07                     289                36   33   
1  2018-07-14                     118                13   50   
2  2018-07-15                     179                51   38   
3  2018-07-16                     279                 5   39   
4  2018-07-23                     289                36   33   

   Daily Work Load Average(in Minutes)   Body Mass Index  Education  Children  \
0                               239.554               30          0         2   
1                               239.554               31          0         1   
2                               239.554               31          0         0   
3                               239.554               24          0         2   
4                               239.554               30          0         2   

   Pets  Absenteeism Time in Hours  Excessive Absenteeism  
0     1                          4                      1  
1     0                          0                      0  
2     0                          2                      0  
3     0                          4                      1  
4     1                          2                      0

In [10]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [16]:
data_with_targets = data_preprocessed.drop(['Date', 'Absenteeism Time in Hours'], axis=1)

In [17]:
data_with_targets.head()

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0        0        0        0        1            7                5   
1        0        0        0        0            7                5   
2        0        0        0        1            7                6   
3        1        0        0        0            7                0   
4        0        0        0        1            7                0   

   Transportation Expense  Distance to Work  Age  \
0                     289                36   33   
1                     118                13   50   
2                     179                51   38   
3                     279                 5   39   
4                     289                36   33   

   Daily Work Load Average(in Minutes)   Body Mass Index  Education  Children  \
0                               239.554               30          0         2   
1                               239.554               31          0         1   
2                               239.554               31          0         0   
3                               239.554               24          0         2   
4                               239.554               30          0         2   

   Pets  Excessive Absenteeism  
0     1                      1  
1     0                      0  
2     0                      0  
3     0                      1  
4     1                      0

In [18]:
data_with_targets.shape[1]

15

In [19]:
data_with_targets.iloc[:,0:14]

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0          0        0        0        1            7                5   
1          0        0        0        0            7                5   
2          0        0        0        1            7                6   
3          1        0        0        0            7                0   
4          0        0        0        1            7                0   
..       ...      ...      ...      ...          ...              ...   
695        1        0        0        0            5                6   
696        1        0        0        0            5                6   
697        1        0        0        0            5                0   
698        0        0        0        1            5                0   
699        0        0        0        1            5                0   

     Transportation Expense  Distance to Work  Age  \
0                       289                36   33   
1                       118                13   50   
2                       179                51   38   
3                       279                 5   39   
4                       289                36   33   
..                      ...               ...  ...   
695                     179                22   40   
696                     225                26   28   
697                     330                16   28   
698                     235                16   32   
699                     291                31   40   

     Daily Work Load Average(in Minutes)   Body Mass Index  Education  \
0                                 239.554               30          0   
1                                 239.554               31          0   
2                                 239.554               31          0   
3                                 239.554               24          0   
4                                 239.554               30          0   
..                                    ...              ...        ...   
695                               237.656               22          1   
696                               237.656               24          0   
697                               237.656               25          1   
698                               237.656               25          1   
699                               237.656               25          0   

     Children  Pets  
0           2     1  
1           1     0  
2           0     0  
3           2     0  
4           2     1  
..        ...   ...  
695         2     0  
696         1     2  
697         0     0  
698         0     0  
699         1     1  

[700 rows x 14 columns]

In [20]:
data_with_targets.iloc[:,0:-1]

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0          0        0        0        1            7                5   
1          0        0        0        0            7                5   
2          0        0        0        1            7                6   
3          1        0        0        0            7                0   
4          0        0        0        1            7                0   
..       ...      ...      ...      ...          ...              ...   
695        1        0        0        0            5                6   
696        1        0        0        0            5                6   
697        1        0        0        0            5                0   
698        0        0        0        1            5                0   
699        0        0        0        1            5                0   

     Transportation Expense  Distance to Work  Age  \
0                       289                36   33   
1                       118                13   50   
2                       179                51   38   
3                       279                 5   39   
4                       289                36   33   
..                      ...               ...  ...   
695                     179                22   40   
696                     225                26   28   
697                     330                16   28   
698                     235                16   32   
699                     291                31   40   

     Daily Work Load Average(in Minutes)   Body Mass Index  Education  \
0                                 239.554               30          0   
1                                 239.554               31          0   
2                                 239.554               31          0   
3                                 239.554               24          0   
4                                 239.554               30          0   
..                                    ...              ...        ...   
695                               237.656               22          1   
696                               237.656               24          0   
697                               237.656               25          1   
698                               237.656               25          1   
699                               237.656               25          0   

     Children  Pets  
0           2     1  
1           1     0  
2           0     0  
3           2     0  
4           2     1  
..        ...   ...  
695         2     0  
696         1     2  
697         0     0  
698         0     0  
699         1     1  

[700 rows x 14 columns]

In [22]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

In [23]:
unscaled_inputs

reason1  reason2  reason3  reason4  Month Value  Day of the Week  \
0          0        0        0        1            7                5   
1          0        0        0        0            7                5   
2          0        0        0        1            7                6   
3          1        0        0        0            7                0   
4          0        0        0        1            7                0   
..       ...      ...      ...      ...          ...              ...   
695        1        0        0        0            5                6   
696        1        0        0        0            5                6   
697        1        0        0        0            5                0   
698        0        0        0        1            5                0   
699        0        0        0        1            5                0   

     Transportation Expense  Distance to Work  Age  \
0                       289                36   33   
1                       118                13   50   
2                       179                51   38   
3                       279                 5   39   
4                       289                36   33   
..                      ...               ...  ...   
695                     179                22   40   
696                     225                26   28   
697                     330                16   28   
698                     235                16   32   
699                     291                31   40   

     Daily Work Load Average(in Minutes)   Body Mass Index  Education  \
0                                 239.554               30          0   
1                                 239.554               31          0   
2                                 239.554               31          0   
3                                 239.554               24          0   
4                                 239.554               30          0   
..                                    ...              ...        ...   
695                               237.656               22          1   
696                               237.656               24          0   
697                               237.656               25          1   
698                               237.656               25          1   
699                               237.656               25          0   

     Children  Pets  
0           2     1  
1           1     0  
2           0     0  
3           2     0  
4           2     1  
..        ...   ...  
695         2     0  
696         1     2  
697         0     0  
698         0     0  
699         1     1  

[700 rows x 14 columns]

In [25]:
pip install -U scikit-learn

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\mohammad\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
absenteeim_scaler = StandardScaler()

In [46]:
absenteeim_scaler.fit(unscaled_inputs)

StandardScaler()

In [75]:
scaled_inputs = absenteeim_scaler.transform(unscaled_inputs)

In [76]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.39626354, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.39626354, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [77]:
scaled_inputs.shape

(700, 14)

In [78]:
from sklearn.model_selection import train_test_split

In [79]:
train_test_split(scaled_inputs,targets)

[array([[-0.57735027, -0.09298136,  2.52357307, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136,  2.52357307, ..., -0.44798003,
          1.78021889, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.39626354, ..., -0.44798003,
         -0.01928035,  0.26848661],
        [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
          0.88046927,  0.26848661]]),
 array([[-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
          2.67996851, -0.58968976],
        [-0.57735027, -0.09298136, -0.39626354, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.39626354, ...,  2.23224237,
         -0.91902997, -0.58968976],
        ...,
        [ 1.73205081, -0.09298136, -0.39626354, ..., -

In [80]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets,train_size = 0.8, test_size = 0.2, random_state = 20)

In [81]:
x_train.shape, y_train.shape

((560, 14), (560,))

In [82]:
x_test.shape, y_test.shape

((140, 14), (140,))

In [88]:
from sklearn.linear_model import LogisticRegression

In [91]:
reg = LogisticRegression()

In [92]:
reg.fit(x_train, y_train)

LogisticRegression()

In [93]:
reg.score(x_train, y_train)

0.8035714285714286

In [94]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [95]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [96]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [97]:
np.sum((model_outputs == y_train))

450

In [98]:
model_outputs.shape[0]

560

In [99]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.8035714285714286